[package]
name = "ReturnOfTheNewChess"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
reqwest = "0.12.24"
thirtyfour = "0.36.1"
tokio = { version = "1.48.0", features = ["full"] }
rand = "0.9.2"
